services:
  postgres:
    image: 'postgres:15'
    container_name: reservify
    environment:
      - 'POSTGRES_DB=reservify'
      - 'POSTGRES_USER=reservify'
      - 'POSTGRES_PASSWORD=reservify'
    ports:
      - '5432:5432'
